config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users,
             { class_name: 'User' }.merge(ActiveAdmin::Devise.config)

  ActiveAdmin.routes(self)

  root to: 'hospitals#show'

  resource :report, only: %i[create]

  resource :hospital, only: %i[show edit update]
  resources :patients, except: %i[destroy]
end

app/models/patient.rb
# frozen_string_literal: true
class Patient < ApplicationRecord
  belongs_to :hospital
  has_one :patient_bed

  accepts_nested_attributes_for :patient_bed, allow_destroy: true

  enum airways: {
    ventilacao_mecanica: 0,
    ar_ambiente: 1,
    ventilacao_nao_invasiva: 2,
  }

  enum departure_reason: {
    alta: 0,
    obito: 1,
    transferencia: 2,
  }

  enum status: {
    suspeito: 0,
    confirmado: 1,
    descartado: 2,
  }

  validates :full_name, presence: true
  validates :airways, presence: true
  validates :hospitalization_date, presence: true
  validates :cns, length: { is: 15 }
  validates :sisreg, length: { is: 9 }

  scope :active, -> { where(departure_reason: nil) }

  def patient_bed_attributes=(attributes)
    self.patient_bed = PatientBed.find(attributes['id']) if attributes['id'].present?

    super
  end
end

app/controllers/patients_controller.rb
# frozen_string_literal: true
class PatientsController < ApplicationController
  def index
    @patients = Patient.paginate(page: params[:page], per_page: 10)
    # @hospital = current_user.hospital
    # @patients = @hospital.patients.paginate(page: params[:page], per_page: 10)
  end

  def show
    @hospital = current_user.hospital
    @patient = @hospital.patients.find(params[:id])
  end

  def new
    @hospital = current_user.hospital
    @patient = @hospital.patients.new
    @patient.build_patient_bed
  end

  def edit
    @hospital = current_user.hospital
    @patient = @hospital.patients.find(params[:id])
    @patient.build_patient_bed if @patient.patient_bed.blank?
  end

  def create
    @hospital = current_user.hospital
    @patient = @hospital.patients.new(
      patient_params.merge(
        patient_bed_attributes: {
          admission_date: patient_params[:hospitalization_date],
        }
      )
    )

    if @patient.save
      redirect_to(patient_url(@patient), notice: 'Patient was successfully created.')
    else
      render(:new)
    end
  end

  def update
    @hospital = current_user.hospital
    @patient = @hospital.patients.find(params[:id])

    if @patient.update(patient_params)
      redirect_to(patient_url(@patient), notice: 'Patient was successfully updated.')
    else
      render(:edit)
    end
  end

  def destroy
    @hospital = Hospital.find(params[:hospital_id])
    @patient = @hospital.patients.find(params[:id])

    @patient.destroy
    redirect_to(patients_url, notice: 'Patient was successfully destroyed.')
  end

  private

  def patient_params
    params.require(:patient).permit(
      :full_name,
      :birthday,
      :hospitalization_date,
      :cns,
      :sisreg,
      :airways,
      :status,
      :departure_date,
      :departure_reason,
      patient_bed_attributes: [:id, :patient_id, :waiting_uti, :bed_type]
    ).merge(hospital: @hospital)
  end
end

app/views/patients/_form.html.erb
<%= form_for @patient, html: { class: "form-horizontal patient patient-form" } do |f| %>

  <%= render partial: 'shared/errors', object: @patient, as: :object %>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :full_name, class: 'control-label' %>
      <%= f.text_field :full_name, class: 'form-control' %>
      <%= f.error_span(:full_name) %>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :birthday, class: 'control-label' %>
      <%= f.date_field :birthday, class: 'form-control' %>
      <%= f.error_span(:birthday) %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-4">
      <%= f.label :hospitalization_date, class: 'control-label' %>
      <%= f.date_field :hospitalization_date, class: 'form-control' %>
      <%= f.error_span(:hospitalization_date) %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :cns, class: 'control-label' %>
      <%= f.text_field :cns, maxlength: 15, class: 'form-control' %>
      <%= f.error_span(:cns) %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :sisreg, class: 'control-label' %>
      <%= f.text_field :sisreg, maxlength: 9, class: 'form-control' %>
      <%= f.error_span(:sisreg) %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-3">
      <%= f.label :status, class: 'control-label' %>
      <%= f.select :status, Patient.human_enum_selectable(:status, Patient.statuses), { }, { class: 'form-control' } %>
      <%= f.error_span(:status) %>
    </div>

    <div class="form-group col-md-3">
      <%= f.label :airways, class: 'control-label' %>
      <%= f.select :airways, Patient.human_enum_selectable(:airways, Patient.airways), { }, { class: 'form-control' } %>
      <%= f.error_span(:airways) %>
    </div>

    <%= f.fields_for :patient_bed, @patient.patient_bed do |b| %>
      <div class="form-group col-md-3">
        <%= f.label :bed_type, 'Tipo de Cama', class: 'control-label' %>
        <%= b.select :bed_type, PatientBed.human_enum_selectable(:bed_type, PatientBed.bed_types), { }, { class: 'form-control' } %>
        <%= f.error_span(:airways) %>
      </div>

      <div class="form-group col-md-3 pt-3">
        <div class="form-check pt-4">
          <%= b.check_box :waiting_uti, class: 'form-check-label' %>
          <%= b.label :waiting_uti, class: 'control-label' %>
          <%= b.error_span(:waiting_uti) %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="form-row">
    <div class="form-group col-md-3">
      <%= f.label :departure_date, class: 'control-label' %>
      <%= f.date_field :departure_date, class: 'form-control' %>
      <%= f.error_span(:departure_date) %>
    </div>

    <div class="form-group col-md-3">
      <%= f.label :departure_reason, class: 'control-label' %>
      <%= f.select :departure_reason, Patient.human_enum_selectable(:departure_reason, Patient.departure_reasons), { include_blank: true }, { class: 'form-control' } %>
      <%= f.error_span(:departure_reason) %>
    </div>
  </div>

   <div class="form-row">
    <div class="form-group col">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to "voltar", patients_path, class:"btn btn-outline-primary" %>
    </div>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<tr>
  <td scope="row">
    <%= link_to patient.full_name, patient_path(patient) %>
  </td>
  <td> <%= patient.birthday ? l(patient.birthday.to_date) : 'Não Informado' %></td>
  <td> <%= patient.hospitalization_date ? l(patient.hospitalization_date.to_date) : 'Não Informado' %> </td>
  <td> <%= Patient.human_enum_name(:airways, patient.airways) %> </td>
  <td> <%= Patient.human_enum_name(:status, patient.status) %> </td>
  <td> <%= patient.cns %> </td>
  <td> <%= patient.sisreg %> </td>
  <td> <%= patient.departure_date ? l(patient.departure_date.to_date) : 'Não Informado' %> </td>
  <td> <%= Patient.human_enum_name(:departure_reason, patient.departure_reason) %> </td>
  <td> <%= PatientBed.human_enum_name(:bed_type, patient.patient_bed.bed_type) if patient.patient_bed %> </td>
  <td> <%= t(patient.patient_bed.waiting_uti) if patient.patient_bed %> </td>
  <td>
    <%= link_to "Editar", edit_patient_path(patient), class:"btn btn-primary" %>
  </td>
</tr>

app/views/patients/_patients.html.erb
<div class="row">
  <div class="col">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Nome</th>
            <th scope="col">Data de Nascimento</th>
            <th scope="col">Data de Internação</th>
            <th scope="col">Vias Aérias</th>
            <th scope="col">COVID-19</th>
            <th scope="col">CSN</th>
            <th scope="col">SiaReg</th>
            <th scope="col">Data de Movimentação</th>
            <th scope="col">Motivo da Movimentação</th>
            <th scope="col">Leito</th>
            <th scope="col">Aguardando UTI?</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render(partial: 'patients/patient', collection: patients) || render(partial: 'shared/empty_table', locals: { colspan: 12, message: 'Nenhum paciente ativo encontrado.' } ) %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/patients/edit.html.erb
<div class="row mb-4">
  <div class="col">
    <h1 class="float-left"><%= t('views.patients.edit.title') %></h1>
    <%= link_to "voltar", patients_path, class:"btn btn-outline-primary float-right" %>
  </div>
</div>

<%= render partial: 'form' %>

app/views/patients/index.html.erb
<div class="row mb-4">
  <div class="col">
    <h1 class="float-left">Pacientes</h1>
    <%= link_to "voltar", hospital_path, class: "btn btn-outline-primary float-right ml-2" %>
    <%= link_to "Adicionar paciente", new_patient_path, class:"btn btn-primary float-right" %>
  </div>
</div>

<%= render partial: 'patients', locals: { patients: @patients } %>

<div class="row">
  <div class="col">
    <%= will_paginate @patients, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/patients/new.html.erb
<div class="row mb-4">
  <div class="col">
    <h1 class="float-left"><%= t('views.patients.new.title') %></h1>
    <%= link_to "voltar", patients_path, class:"btn btn-outline-primary float-right" %>
  </div>
</div>

<%= render partial: 'form' %>

app/views/patients/show.html.erb
<div class="row mb-4">
  <div class="col">
    <h1 class="float-left">Paciente (<%= @patient.full_name %>)</h1>
    <%= link_to "voltar", patients_path, class: "btn btn-outline-primary float-right ml-2" %>
    <%= link_to "editar paciente", edit_patient_path(@patient), class:"btn btn-primary float-right" %>
  </div>
</div>
<div class="row">
  <div class="col">
    <form>
      <div class="form-group">
        <div class="row">
          <div class="col-form-label col-md-6">
            <label for="full_name">Nome completo</label>
            <input type="text" class="form-control" id="full_name" value="<%= @patient.full_name %>" aria-describedby="full_name" readonly>
          </div>
          <div class="col-form-label col-md-6">
            <label for="birthday">Data de Nascimento</label>
            <input type="text" class="form-control" id="birthday" value="<%= l(@patient.birthday, default: 'Não informado') %>" aria-describedby="birthday" readonly>
          </div>
        </div>
        <div class="row">
          <div class="col-form-label col-md-4">
            <label for="hospitalization_date">Data de Hospitalização</label>
            <input type="text" class="form-control" id="hospitalization_date" aria-describedby="hospitalization_date" value="<%= l(@patient.hospitalization_date, format: :long, default: 'Não informado') %>" readonly>
          </div>
          <div class="col-form-label col-md-4">
            <label for="cns">Carteira do SUS</label>
            <input type="text" class="form-control" id="cns" aria-describedby="cns" value="<%= @patient.cns %>" readonly>
          </div>
          <div class="col-form-label col-md-4">
            <label for="sisreg">Sisreg</label>
            <input type="text" class="form-control" id="sisreg" aria-describedby="sisreg" value="<%= @patient.sisreg %>" readonly>
          </div>
        </div>
        <div class="row">
          <div class="col-form-label col-md-6">
            <label for="status">Status</label>
            <input type="text" class="form-control" id="status" aria-describedby="status" value="<%= Patient.human_enum_name(:status, @patient.status) %>" readonly>
          </div>
          <div class="col-form-label col-md-6">
            <label for="airways">Ventilação</label>
            <input type="text" class="form-control" id="airways" aria-describedby="airways" value="<%= Patient.human_enum_name(:airways, @patient.airways) %>" readonly>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
<div class="row mb-4 mt-4">
  <div class="col">
    <h1 class="float-left">Leito</h1>
  </div>
</div>
<div class="row">
  <div class="col">
    <form>
      <div class="form-group">
        <div class="row">
          <div class="col-form-label col-md-6">
            <label for="bed_type">Tipo de Cama</label>
            <input type="text" class="form-control" id="bed_type" aria-describedby="bed_type" value="<%= PatientBed.human_enum_name(:bed_type, @patient.patient_bed&.bed_type) || 'Não informado' %>" readonly>
          </div>
          <div class="col-form-label col-md-6">
            <label for="waiting_uti">Aguardando UTI?</label>
            <input type="text" class="form-control" id="waiting_uti" aria-describedby="waiting_uti" value="<%= @patient.patient_bed ? @patient.patient_bed.waiting_uti ? 'Sim' : 'Não' : 'Não informado' %>" readonly>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
<div class="row mb-4 mt-4">
  <div class="col">
    <h1 class="float-left">Movimentação</h1>
  </div>
</div>
<div class="row">
  <div class="col">
    <form>
      <div class="form-group">
        <div class="row">
          <div class="col-form-label col-md-6">
            <label for="departure_date">Data de Movimentação</label>
            <input type="text" class="form-control" id="departure_date" aria-describedby="departure_date" value="<%= l(@patient.departure_date, format: :long, default: 'Não informado') %>" readonly>
          </div>
          <div class="col-form-label col-md-6">
            <label for="departure_reason">Motivo da Movimentação</label>
            <input type="text" class="form-control" id="departure_reason" aria-describedby="departure_reason" value="<%= Patient.human_enum_name(:departure_reason, @patient.departure_reason) %>" readonly>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>