config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users,
             { class_name: 'User' }.merge(ActiveAdmin::Devise.config)

  ActiveAdmin.routes(self)

  root to: 'hospitals#show'

  resource :report, only: %i[create]

  resource :hospital, only: %i[show edit update]
  resources :patients, except: %i[destroy]
end

app/models/hospital.rb
# frozen_string_literal: true
class Hospital < ApplicationRecord
  has_many :hospital_beds, dependent: :nullify
  has_many :patients
  has_many :reports
  has_many :users

  accepts_nested_attributes_for :hospital_beds, allow_destroy: true

  validates :acronym, presence: true, length: { maximum: 8 }
  validates :city, presence: true
  validates :email, presence: true, email_format: true
  validates :name, presence: true, length: { maximum: 256 }
  validates :phone_number, phone: { allow_blank: true }

  after_commit -> { create_hospital_beds }, on: :create

  def self.current_id
    Thread.current[:hospital_id]
  end

  def self.current_id=(hospital_id)
    Thread.current[:hospital_id] = hospital_id
  end

  private

  def create_hospital_beds
    HospitalBedService.new(hospital_id: id).create_beds!
  end
end

app/controllers/hospitals_controller.rb
# frozen_string_literal: true
class HospitalsController < ApplicationController
  def show
    @hospital = current_user.hospital
    @patients = @hospital.patients.active.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @hospital = current_user.hospital
    @hospital_beds = @hospital.hospital_beds
  end

  def update
    update_hospital_beds

    @hospital = current_user.hospital
    @hospital_beds = @hospital.hospital_beds

    if @hospital.update(hospital_params)
      redirect_to(@hospital, notice: 'Hospital was successfully updated.')
    else
      render(:edit)
    end
  end

  private

  def update_hospital_beds
    params.require(:hospital_beds).each do |id, payload|
      current_user.hospital.hospital_beds.find(id).update!(payload.permit(:total, :total_covid))
    end
  end

  def hospital_params
    params.require(:hospital).permit(:acronym, :name, :city, :phone_number, :email, :private)
  end
end

app/views/hospitals/_form.html.erb
<div class="row">
  <div class="col">
    <%= form_for @hospital, html: { class: "form-horizontal hospital" } do |f| %>

      <%= render partial: 'shared/errors', object: @hospital, as: :object %>

      <div class="form-row">
        <div class="form-group col-md-6">
          <%= f.label :name, "Nome" %>
          <%= f.text_field :name, class: 'form-control' %>
          <%= f.error_span(:name) %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label :city, "Cidade" %>
          <%= f.text_field :city, class: 'form-control' %>
          <%= f.error_span(:city) %>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6">
          <%= f.label :phone_number, "Telefone" %>
          <%= f.text_field :phone_number, class: 'form-control' %>
          <%= f.error_span(:phone_number) %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label :email, "E-mail" %>
          <%= f.text_field :email, class: 'form-control' %>
          <%= f.error_span(:email) %>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6">
          <%= f.label :acronym, "Acrônimo" %>
          <%= f.text_field :acronym, class: 'form-control' %>
          <%= f.error_span(:acronym) %>
        </div>

        <div class="form-group col-md-6 pt-3">
          <div class="form-check pt-4">
            <%= f.check_box :private, class: 'form-check-label' %>
            <%= f.label :private, 'hospital privado?', class: 'control-label' %>
            <%= f.error_span(:private) %>
          </div>
        </div>
      </div>

      <% @hospital_beds.each do |hospital_bed| %>
          <div class="row">
            <div class="col">
              <b><%= HospitalBed.human_enum_name(:bed_type, hospital_bed.bed_type) %></b>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-6">
              <%= fields_for 'hospital_beds[]', hospital_bed do |hf| %>
                <%= hf.label :total, 'Total' %>
                <%= hf.text_field :total, class: 'form-control' %>
            </div>
            <div class="form-group col-md-6">
                <%= hf.label :total, 'Total COVID-19' %>
                <%= hf.text_field :total_covid, class: 'form-control' %>
            </div>
          </div>
        <% end %>
      <% end %>

      <div class="form-row">
        <div class="form-group col">
          <%= f.submit "Atualizar dados", class: 'btn btn-primary' %>
          <%= link_to "voltar", hospital_path, class: "btn btn-outline-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/hospitals/_info.html.erb
<div class="row">
  <div class="col">
    <form>
      <div class="form-group">
        <div class="row">
          <div class="col-form-label col-md-6">
            <label for="hospital">Hospital</label>
            <input type="text" class="form-control" id="hospital" value="<%= hospital.name %>" aria-describedby="hospital" readonly>
          </div>
          <div class="col-form-label col-md-6">
            <label for="city">Município</label>
            <input type="text" class="form-control" id="city" value="<%= hospital.city %>" aria-describedby="city" readonly>
          </div>
        </div>
        <div class="row">
          <div class="col-form-label col-md-6">
            <label for="phone_number">Telefone</label>
            <input type="text" class="form-control" id="phone_number" aria-describedby="phone_number" value="<%= hospital.phone_number %>" readonly>
          </div>
          <div class="col-form-label col-md-6">
            <label for="email">E-mail</label>
            <input type="email" class="form-control" id="email" aria-describedby="email" value="<%= hospital.email %>" readonly>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

app/views/hospitals/_statistics.html.erb
<div class="row">
  <div class="col">
    <div class="form-group">
      <div class="row mb-3">
        <% hospital_beds.each do |hospital_bed| %>
          <div class="col-3">
            <label><%= HospitalBed.human_enum_name(:bed_type, hospital_bed.bed_type) %></label>
            <input type="text" class="form-control" id="hospital" value="<%= hospital_bed.total %>" aria-describedby="hospital" readonly>
            <span class="text-muted">
              dos quais <%= hospital_bed.total_covid %> são de COVID-19
            </span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/hospitals/edit.html.erb
<div class="row mb-4">
  <div class="col">
    <h1 class="float-left">Editar Dados Gerais do Hospital</h1>
    <%= link_to "voltar", hospital_path, class: "btn btn-outline-primary float-right" %>
  </div>
</div>

<%= render partial: 'form' %>

app/views/hospitals/show.html.erb
<div class="row mb-4">
  <div class="col">
    <h1 class="float-left">Dados Gerais (<%= @hospital.acronym %>)</h1>
    <%= link_to "editar dados do hospital", edit_hospital_path, class:"btn btn-outline-primary float-right" %>
  </div>
</div>

<%= render partial: 'info', locals: { hospital: @hospital } %>

<div class="row mb-4 mt-4">
  <div class="col">
    <h1 class="float-left">Ocupação de Leitos</h1>
    <%= link_to "editar dados de ocupação", edit_hospital_path, class:"btn btn-outline-primary float-right" %>
  </div>
</div>

<%= render partial: 'statistics', locals: { hospital_beds: @hospital.hospital_beds } %>

<div class="row mb-4 mt-4">
  <div class="col">
    <h1 class="float-left">Pacientes</h1>
    <%= link_to "atualizar dados dos pacientes", patients_path, class:"btn btn-outline-primary float-right" %>
  </div>
</div>

<%= render partial: 'patients/patients', locals: { patients: @patients } %>

<div class="row">
  <div class="col">
    <%= will_paginate @patients, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

<div class="row">
  <div class="col">
    <%= link_to "Enviar Relatório", "#", class: 'btn btn-primary float-right' %>
  </div>
</div>